version: 0.9.1.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: CodeMaid.sln
  verbosity: minimal
test:
  assemblies:
    - SteveCadwallader.CodeMaid.UnitTests.dll
    - SteveCadwallader.CodeMaid.IntegrationTests.dll